import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "../styles/globals.scss";
import Providers from "@/context/Providers";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session: any
}>) {

  return (
    <html lang="en" >
      <body className={nunito.className}>
        <Providers session={session}>
            <main>
              {children}
            </main>
        </Providers>
      </body>
    </html>
  );
}
