import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";
import { getSession } from "@/configs/next-auth";
 
 
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {
  const session = await getSession()  
  return (
    <html lang="en" >
      <body className={nunito.className}>
        <Providers session={session}>
          <main>
          {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
